# Web UI pro headscale

server:

  # headplane web server
  host: 0.0.0.0
  port: 3000
  cookie_secret: CHANGE_ME_32_CHARS

headscale:

  # interní docker komunikace
  # neměnit pokud běží ve stejném compose
  url: http://headscale:8080


