server_url: https://vpn.corp.cz
listen_addr: 0.0.0.0:8080

noise:
  private_key_path: /var/lib/headscale/noise_private.key

database:
  type: sqlite
  sqlite:
    path: /var/lib/headscale/db.sqlite

prefixes:
  v4: 100.64.0.0/10

dns:
  magic_dns: true
  override_local_dns: true
  base_domain: tailnet.local
  nameservers:
    global:
      - 192.168.1.1
  search_domains:
    - corp.local
derp:
  urls:
    - https://controlplane.tailscale.com/derpmap/default

policy:
  mode: file
  path: /etc/headscale/acl.json
